# Generated by Django 5.2.6 on 2025-09-12 16:03

import auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, help_text='Уникальный идентификатор клиента', max_length=128, unique=True, verbose_name='ID клиента')),
                ('client_secret', models.CharField(default=auth.models._get_token, editable=False, help_text='Секретный ключ клиента', max_length=128, verbose_name='Secret клиента')),
                ('comment', models.CharField(help_text='Имя клиента или пояснение', max_length=256, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, help_text='Указывает, может ли клиент посылать письма', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Момент изменения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
