# Generated by Django 5.2.6 on 2025-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(help_text='Уникальный идентификатор клиента', max_length=128, unique=True, verbose_name='ID клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, help_text='Имя клиента или пояснение', max_length=256, null=True, verbose_name='Комментарий'),
        ),
    ]
